on:
  push:
    branches: [master]

name: Deploy rustdoc

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Store SSH Keys
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.key_private }}

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build docs
        run: cargo doc --document-private-items
        
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://161.35.234.130:22
          ftp-username: clientDocFtp
          known-hosts: 161.35.234.130:22 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFvqOX8oO2T90meS1mvGSkuCjyakuFf079+q1TwYXEQdxw7bmBLO2WpzKF/aWILMbjl2nb5p0kAf5onVOOpFuu0=
          local-dir: target/doc
          git-ftp-args: --remote-root "/var/www/TODO/doc/client-rust/" --key "~/.ssh/id_rsa"
